[toolchain]
channel = "stable"
components = ["rustfmt", "clippy"]
targets = ["x86_64-unknown-linux-gnu"]

[toolchain.nightly]
channel = "nightly"
components = ["rustfmt", "rustfmt-preview"]
targets = ["x86_64-unknown-linux-gnu"] 