[package]
name = "jd_utils"
version = "0.1.0"
edition = "2024"

[dependencies]
derive_more.workspace = true
serde.workspace = true
serde_with.workspace = true
time.workspace = true

config = "0.15.11"
regex = "1.11.1"
