version: '3.9'

services:
  eamon-server:
    container_name: jaydenblog
    image: postgres:latest
    restart: always
    env_file:
      - ../.env
      - ../.env.docker
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
