version: '3.8'

services:
  postgres:
    build:
      context: ../..
      dockerfile: deployment/docker/Dockerfile.postgres
    environment:
      - POSTGRES_USER=jayden
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=jayden-blog
      - INIT_DB=${INIT_DB:-true}  # Default to true for dev, can be overridden
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jayden -d jaydenblog"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    container_name: jd-redis
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  postgres_data:
  redis-data:
