[package]
name = "web_server"
version = "0.1.0"
edition = "2024"

[dependencies]
axum.workspace = true
serde.workspace = true
tokio.workspace = true
tracing.workspace = true

tracing-subscriber = "0.3.19"
