-- Update timestamp columns to TIMESTAMPTZ
ALTER TABLE users 
    ALTER COLUMN created_at TYPE TIMESTAMPTZ,
    ALTER COLUMN updated_at TYPE TIMESTAMPTZ;

ALTER TABLE user_profiles 
    ALTER COLUMN created_at TYPE TIMESTAMPTZ,
    ALTER COLUMN updated_at TYPE TIMESTAMPTZ;

ALTER TABLE user_subscriptions 
    ALTER COLUMN created_at TYPE TIMESTAMPTZ,
    ALTER COLUMN updated_at TYPE TIMESTAMPTZ,
    ALTER COLUMN start_date TYPE TIMESTAMPTZ,
    ALTER COLUMN end_date TYPE TIMESTAMPTZ;

ALTER TABLE user_devices 
    ALTER COLUMN created_at TYPE TIMESTAMPTZ,
    ALTER COLUMN updated_at TYPE TIMESTAMPTZ,
    ALTER COLUMN first_seen_at TYPE TIMESTAMPTZ,
    ALTER COLUMN last_seen_at TYPE TIMESTAMPTZ;

ALTER TABLE user_engagement_metrics 
    ALTER COLUMN created_at TYPE TIMESTAMPTZ,
    ALTER COLUMN updated_at TYPE TIMESTAMPTZ,
    ALTER COLUMN last_login_at TYPE TIMESTAMPTZ,
    ALTER COLUMN last_computed_at TYPE TIMESTAMPTZ;

ALTER TABLE user_preferences 
    ALTER COLUMN created_at TYPE TIMESTAMPTZ,
    ALTER COLUMN updated_at TYPE TIMESTAMPTZ,
    ALTER COLUMN consent_date TYPE TIMESTAMPTZ; 