name: Code Quality & Tests

on:
  pull_request:
    branches: ["main"]

  push:
    branches: ["main", "dev"]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        # Có thể thêm các OS khác nếu cần
        # os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-test-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-cargo-test-
      
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      
      - name: Install dependencies
        if: runner.os == 'linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y alsa-utils libasound2-dev udev
      
      - name: Install cargo-nextest
        run: cargo install cargo-nextest --force
      
      - name: Run tests
        run: cargo nextest run --workspace

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-lint-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-cargo-lint-
      
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt, clippy
      
      - name: Run clippy
        run: cargo clippy --workspace --all-targets --all-features
      
      - name: Check format
        run: cargo fmt --all -- --check
